# (Tokyo Night) color scheme for Emilia Rice

# Default colors
[colors.primary]
#background = "#1a1b26"
background = "#080809"
foreground = "#a9b1d6"

# Cursor colors
[colors.cursor]
cursor = "#bb9af7"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#32344a"
# blue = "#7aa2f7"
blue = "#1271f7"
cyan = "#449dab"
green = "#25D366"
magenta = "#ffffff"
red = "#f7768e"
# white = "#787c99"
white = "#dddddd"
yellow = "#e0af68"

# Bright colors
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"
